### PR TITLE
runTrace: Output to stderr.

### PR DESCRIPTION
**Pull request by shlevy**
stderr is the semantically appropriate stream for trace messages

### CODE REVIEW

**Comment by xkollar** [comment]
Hi @shlevy,
Thanks for PR. Would #30 solve your problem?

**Comment by shlevy** [comment]
@xkollar if `runTraceIO` in that PR used `hPutStrLn stderr` it would, yes

**Comment by xkollar** [comment]
@shlevy: be12fd1fcffca6233c1702576bcf00e008112994 is now part of #30.

**Comment by shlevy** [comment]
Thanks!

**Pull request closed without merging**
